name: Run Auto Script

on:
 # schedule:
 #   - cron: '0 0 * * *' # 可根据需要自行调整定时规则（例如每天执行一次）
  workflow_dispatch:     # 支持在 GitHub 仓库 Actions 页面手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install seleniumbase requests

      - name: 启用 WARP 网络
        uses: fscarmen/warp-on-actions@v1.3
        with:
          stack: dual
          mode: client

      - name: Run main script
        env:
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          FIXED_PASSWORD: ${{ secrets.FIXED_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python main.py
